Fix the example code of OpenAPI 2 (api-description.yml) in Quickstart page
Dredd cannot parse the api-description.yml on the Quickstart page currently.

```
> dredd .\api-description.yml http://localhost:3000
error: Parser error in file './api-description.yml': Cannot read property 'version' of null on line 1
error: Error when processing API description.
```

The problem is caused by the grammatical error of yaml file.
Therefore I update the file using Swagger Editor.